ProCsharp/MvcDemo/MvcDemo/Controllers/MoviesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcDemo.Models;
using System.Threading;

namespace MvcDemo.Controllers
{
    //[Authorize]     // Instead of just at the Action level, the attrb can be applied to the controller as a whole.
    public class MoviesController : Controller
    {
        private MovieDBContext db = new MovieDBContext();

        //
        // GET: /Movies/

        public ViewResult Index()
        {
            ViewBag.Movies = db.Movies.Select(r => r.Title).Distinct(); // to get MovieReview on the home page
            return View(db.Movies.ToList());
        }

        public PartialViewResult Search(string q)
        {
            var movies = db.Movies.Where(r => r.Title.Contains(q) || string.IsNullOrEmpty(q)).Take(5);
            return PartialView("_MovieSearchResults", movies);
        }

        // Defining the function for the autocomplete
        public ActionResult QuickSearch(string term)
        {
            var movies = db.Movies.Where(r => r.Title.Contains(term)).Take(5).Select(r => new { label = r.Title });
            return Json(movies, JsonRequestBehavior.AllowGet);
        }


        public PartialViewResult MovieReview()
        {
            Thread.Sleep(2000);
            var review = "This is a test review text";
            ViewBag.Title = "Movie1";
            ViewBag.Review = review;
            return PartialView("_Review");
            
        }

        //
        // GET: /Movies/Details/5

        public ViewResult Details(int id)
        {
            MovieDB moviedb = db.Movies.Find(id);
            return View(moviedb);
        }

        //
        // GET: /Movies/Create

        public ActionResult Create()
        {
            return View();
        } 

        //
        // POST: /Movies/Create

        [HttpPost]
        public ActionResult Create(MovieDB moviedb)
        {
            if (ModelState.IsValid)
            {
                db.Movies.Add(moviedb);
                db.SaveChanges();
                return RedirectToAction("Index");  
            }

            return View(moviedb);
        }
        
        //
        // GET: /Movies/Edit/5
 
        public ActionResult Edit(int id)
        {
            MovieDB moviedb = db.Movies.Find(id);
            return View(moviedb);
        }

        //
        // POST: /Movies/Edit/5

        [HttpPost]
        public ActionResult Edit(MovieDB moviedb)
        {
            if (ModelState.IsValid)
            {
                db.Entry(moviedb).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(moviedb);
        }

        //
        // GET: /Movies/Delete/5
 
        public ActionResult Delete(int id)
        {
            MovieDB moviedb = db.Movies.Find(id);
            return View(moviedb);
        }

        //
        // POST: /Movies/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {            
            MovieDB moviedb = db.Movies.Find(id);
            db.Movies.Remove(moviedb);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

ProCsharp/MvcDemo/MvcDemo/Views/Movies/Create.cshtml
@model MvcDemo.Models.MovieDB

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>MovieDB</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Title)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Title)
            @Html.ValidationMessageFor(model => model.Title)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Director)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Director)
            @Html.ValidationMessageFor(model => model.Director)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Review)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Review)
            @Html.ValidationMessageFor(model => model.Review)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Date)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Date)
            @Html.ValidationMessageFor(model => model.Date)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Test_Property)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Test_Property)
            @Html.ValidationMessageFor(model => model.Test_Property)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ProCsharp/MvcDemo/MvcDemo/Views/Movies/Delete.cshtml
@model MvcDemo.Models.MovieDB

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>MovieDB</legend>

    <div class="display-label">Title</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Title)
    </div>

    <div class="display-label">Director</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Director)
    </div>

    <div class="display-label">Review</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Review)
    </div>

    <div class="display-label">Date</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Date)
    </div>

    <div class="display-label">Test_Property</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Test_Property)
    </div>

</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

ProCsharp/MvcDemo/MvcDemo/Views/Movies/Details.cshtml
@model MvcDemo.Models.MovieDB

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>MovieDB</legend>

    <div class="display-label">Title</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Title)
    </div>

    <div class="display-label">Director</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Director)
    </div>

    <div class="display-label">Review</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Review)
    </div>

    <div class="display-label">Date</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Date)
    </div>

    <div class="display-label">Test_Property</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Test_Property)
    </div>

</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ProCsharp/MvcDemo/MvcDemo/Views/Movies/Edit.cshtml
@model MvcDemo.Models.MovieDB
@{
    ViewBag.Title = "Edit";
}
<h2>
    Edit</h2>
@section scripts {
    <script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
}
@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>MovieDB</legend>
        @Html.HiddenFor(model => model.ID)
        <div class="editor-label">
            @Html.LabelFor(model => model.Title)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Title)
            @Html.ValidationMessageFor(model => model.Title)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.Director)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Director)
            @Html.ValidationMessageFor(model => model.Director)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.Review)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Review)
            @Html.ValidationMessageFor(model => model.Review)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.Date)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Date)
            @Html.ValidationMessageFor(model => model.Date)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.Test_Property)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Test_Property)
            @Html.ValidationMessageFor(model => model.Test_Property)
        </div>
        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ProCsharp/MvcDemo/MvcDemo/Views/Movies/Index.cshtml
@model IEnumerable<MvcDemo.Models.MovieDB>
@{
    ViewBag.Title = "Index";
}

@Content.Script("jquery-1.5.1.min.js", Url)
@Content.Script("jquery.unobtrusive-ajax.min.js", Url)
@Content.Script("modernizr-1.7.min.js", Url)
<h2>
    Index</h2>
<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th>
            Title
        </th>
        <th>
            Director
        </th>
        <th>
            Review
        </th>
        <th>
            Date
        </th>
        <th>
            Test_Property
        </th>
        <th>
        </th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.ActionLink(item.Title, "Details", "Movies", new { id = item.ID }, null)
                <!--@Html.DisplayFor(modelItem => item.Title)-->
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Director)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Review)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Test_Property)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.ID }) | @* @Html.ActionLink("Details", "Details", new { id=item.ID }) *@
                @Html.ActionLink("Movie Review", "MovieReview", new { id = item.ID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.ID })
            </td>
        </tr>
    }
</table>
@using (Html.BeginForm())
{
    @Html.DropDownList("movieTitle", new SelectList(ViewBag.Movies))
    <input type="submit" value="Filter" />
}
<div id="movieReview">
    <!-- Using Ajax renders HTML with data- attributes which can be used by javascripts
    to hook into it and make it behave asynchronously -->
    @Ajax.ActionLink("Click here to see the latest review",
                    "MovieReview",
                    "Movies",
                    new AjaxOptions
                    {
                        UpdateTargetId = "movieReview",
                        InsertionMode = InsertionMode.Replace,
                        HttpMethod = "GET",
                        LoadingElementId = "progress"
                    })
</div>

<!-- Let us now put a search box for the movies using Ajax -->
        
@using (Ajax.BeginForm("Search", "Movies", new AjaxOptions
{
    HttpMethod = "GET",
    InsertionMode = InsertionMode.Replace,
    UpdateTargetId = "searchResults"
}))
{
    <input type="text" name="q" data-autocomplete="@Url.Action("QuickSearch", "Movies")" />
    <input type="submit" value="Search" />
}

<table id="searchResults">

</table>

<div id="progress">
    <img src="../../Content/themes/base/images/TestImage.bmp" />
</div>